### ISSUE TITLE
Authlib-injector

### ISSUE THREAD

**Issue by Wonkiest29** [mindstorm38/portablemc#211] opened 2024-04-18 23:39 UTC
Add func for https://github.com/yushijinhun/authlib-injector

**Comment by mindstorm38** [comment] 2024-04-19 08:39
Please explain a bit more your request!

**Comment by Wonkiest29** [comment] 2024-04-20 18:06
i mean add function like for authlib custom

**Comment by Ristovski** [comment] 2024-04-20 18:38
@Wonkiest29 That still doesn't explain what the exact functionality you would like is.

**Comment by mindstorm38** [comment] 2024-04-20 18:39
Sorry, but I don't really know for what authlib-injector is used. You mean that you should be able to add the JAR manually to the game's classpath?

**Comment by Ristovski** [comment] 2024-04-20 18:45
From what I can gather, authlib-injector allows you to create your own custom auth server instead of using the Mojang one. The problem is, in order to work it would explicitly need to be supported by the launcher as well in order to pass the tokens (and the jar is loaded as a java agent to "patch" the Java-side).

Seems like out of scope for PMC as this functionality should be implemented as an addon or custom script via the API instead.

**Comment by mindstorm38** [comment] 2024-04-21 09:51
Ok I see, it seems a bit complicated actually

**Comment by Wonkiest29** [comment] 2024-04-21 17:40
> @Wonkiest29 That still doesn't explain what the exact functionality you would like is.

sorry, i mean add func for custom auth mojang yea i know that require additional server like auth server but probable need in launcher too

**Comment by mindstorm38** [comment] 2024-04-23 18:49
Allowing custom authentication is an interesting topic, however this issue is not descriptive enough for me to really understand what's currently missing in the launcher. It looks like authlib-injector can be enabled with the java agent and JVM arguments, which can already be specified using `--jvm-args` argument when starting the game.

**Comment by Wonkiest29** [comment] 2024-04-23 23:59
you think will be work via args? okay maybe i try smth and make PR

**Comment by Ristovski** [comment] 2024-04-24 14:46
@mindstorm38 From what I can tell, the injected jar only serves the purpose to make Minecraft aware of the custom authentication when verifying the tokens it receives from the launcher.

To have this fully working, there would need to be launcher-side functionality that actually "logs in" with the custom authentication.

Hence why I said this should be an addon to PMC rather than a core functionality, as I feel like its out of scope for the base launcher itself.

**Comment by mindstorm38** [comment] 2024-04-25 11:11
Yes it feels a bit out of scope but it can still be relevant to have some command line flags, like uuid and username, to give a custom token?

**Comment by Wonkiest29** [comment] 2024-04-28 22:54
> Yes it feels a bit out of scope but it can still be relevant to have some command line flags, like uuid and username, to give a custom token?

But that need inject authlib

**Closed** 2024-09-12 12:05 UTC
Labels: triage
