### ISSUE TITLE
Microsoft Login

### ISSUE THREAD

**Issue by matthewperiut** [mindstorm38/portablemc#13] opened 2021-06-03 23:57 UTC
I'm unsure if this launcher let's you login using the new standard Microsoft accounts

**Comment by mindstorm38** [comment] 2021-06-04 07:49
I was planning to work on that when I will be migrated, but it seems that my account has not yet migrated! Also, I don't know how this works, what API to use and what to get... If anyone knows, please comment this issue !

**Comment by mindstorm38** [comment] 2021-06-04 14:01
There are some info there : https://wiki.vg/Microsoft_Authentication_Scheme
I will try to implement that for the next release!

**Comment by mindstorm38** [comment] 2021-06-06 14:02
This is way harder than what I expected, but this will be in the next release because it's a critical need for Minecraft players in 2021 and will be mandatory for the next years.

**Comment by mindstorm38** [comment] 2021-06-10 12:32
I'm actively working on Microsoft authentication. There are still many issues because the Microsoft and Xbox Live documentation is really missing important parts.

**Comment by matthewperiut** [comment] 2021-06-10 23:56
I've realized how difficult this issue is because MultiMC hasn't even implemented it either

**Comment by mindstorm38** [comment] 2021-06-10 23:58
Ahaha true! But I will tag a pre-release of the next version soon with a work-in-progress version of MS authentication :)

**Comment by mindstorm38** [comment] 2021-06-14 19:53
Pre-release tomorrow.

**Comment by mindstorm38** [comment] 2021-06-15 21:19
Please test the fix in the [latest pre-release](https://github.com/mindstorm38/portablemc/releases/tag/v1.1.4-pre1).
Commentez ce problème s'il est résolu ou non.

**Comment by mindstorm38** [comment] 2021-07-03 13:20
Please test the feature or fix in the [latest pre-release](https://github.com/mindstorm38/portablemc/releases/tag/v1.1.4-pre2).
Comment this issue if the problem is fixed or not. This issue will be closed before the final release 1.1.4 if no problems are discovered.

**Comment by mindstorm38** [comment] 2021-07-07 08:21
Release 1.4 soon.

**Comment by mindstorm38** [comment] 2021-07-07 08:22
Release 1.4 soon

**Closed** 2021-07-07 08:22 UTC
Labels: bug, enhancement, pre-released
