### ISSUE TITLE
JAR tool not found on startup

### ISSUE THREAD

**Issue by allen546** [mindstorm38/portablemc#156] opened 2023-07-27 04:56 UTC
I'm looking into using portablemc as my daily launcher, but I've found an issue that prevents me from starting:
When I'm starting up `portablemc start -u allen`, there's an error telling me FileNotFoundError: no such file: /Library/application support/minecraft/jvm/java-runtime-gamma/jre.bundle/Contents/home/bin/jar
This is probably the Jar exe, but I could start up before using Launcher, so I'm not sure what happened. A deeper investigation revealed that there was no jre.bundle .
the error is on portablemc/__init__.py, line 568: os.chmod(exec_file, 0o777)
I'm on macOS, and my Java installation is at /Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home/bin/jar
I think this is a bug, but I'm new to portablemc, so ill just report the facts :)

**Comment by allen546** [comment] 2023-07-27 04:58
Also, when I resolved to giving portablemc the location of jar, it gave me "Illegal Option: X", seems to be from the jar tool. I resolved to using the location of `java`.

**Comment by mindstorm38** [comment] 2023-07-27 07:49
Thank you for that report! It's not the first time someone encounters an issue with auto installation of Mojang's JVM on macOS... I don't really understand it because if it happens on chmod, this mean that the metadata given by Mojang is wrong... This metadata gives which file to download and if it's an executable or not. 

I'll definitely fix this for the next v4 update, I expect to publish pre-release of it this weekend.

**Comment by mindstorm38** [comment] 2023-07-29 20:38
Sorry but the first pre-release doesn't fix your issue, I was a bit too optimistic

**Comment by mindstorm38** [comment] 2023-07-30 10:36
Should be fixed by latest pre-release: https://github.com/mindstorm38/portablemc/issues/146#issuecomment-1657103767

Can you tell me if the problem is fixed?

**Comment by mindstorm38** [comment] 2023-07-30 13:26
Sorry... I was tired and made a typo which break jvm path only on macOS..........

**Comment by mindstorm38** [comment] 2023-08-05 09:39
Should be fixed on v4

**Closed by mindstorm38** 2023-08-05 09:39 UTC
Labels: bug

**Comment by mindstorm38** [comment] 2023-08-05 10:45
Released!
Changelog: https://github.com/mindstorm38/portablemc/releases/tag/v4.0.0
Release page: https://pypi.org/project/portablemc/4.0.0/
Install with `pip install portablemc==4.0.0`

**Comment by allen546** [comment] 2023-08-06 07:23
Thanks for helping me, I just reported this as a bug and I used a hack to make it work by manually giving the JVM path if os.name == “darwin”
Anyway, it looks better now. Thanks

On Aug 5, 2023, at 18:45, Théo Rozier ***@***.***> wrote:



Released!
Changelog: https://github.com/mindstorm38/portablemc/releases/tag/v4.0.0
Release page: https://pypi.org/project/portablemc/4.0.0/
Install with pip install portablemc==4.0.0
